---
platform: linux

image_resource:
  type: docker-image
  source: {repository: cloudfoundry/cflinuxfs2}

outputs:
- name: terraform

params:
  TERRAFORM_ZIP_URL:

run:
  path: pcf-pipelines/tasks/get-dependencies/terraform/task.sh
