---
platform: linux

image_resource:
  type: docker-image
  source: {repository: czero/cflinuxfs2}

inputs:
- name: pcf-pipelines

params:
  PRODUCT_NAME:
  OPSMAN_URI:
  OPSMAN_USERNAME:
  OPSMAN_PASSWORD:
  OPSMAN_CLIENT_ID:
  OPSMAN_CLIENT_SECRET:
  ERRANDS_TO_DISABLE:

run:
  path: pcf-pipelines/tasks/disable-errands/task.sh
