
---
resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final

resources:
- name: binary-buildpack-latest
  type: pivnet
  check_every: {{poll_interval}}
  source:
    api_token: {{pcf_pivnet_token}}
    product_slug: buildpacks
    product_version: "Binary*"

- name: dotnetcore-buildpack-latest
  type: pivnet
  check_every: {{poll_interval}}
  source:
    api_token: {{pcf_pivnet_token}}
    product_slug: buildpacks
    product_version: ".NET Core*"

- name: go-buildpack-latest
  type: pivnet
  check_every: {{poll_interval}}
  source:
    api_token: {{pcf_pivnet_token}}
    product_slug: buildpacks
    product_version: "Go*"

- name: java-buildpack-latest
  type: pivnet
  check_every: {{poll_interval}}
  source:
    api_token: {{pcf_pivnet_token}}
    product_slug: buildpacks
    product_version: "Java*"

- name: nodejs-buildpack-latest
  type: pivnet
  check_every: {{poll_interval}}
  source:
    api_token: {{pcf_pivnet_token}}
    product_slug: buildpacks
    product_version: "NodeJS*"

- name: php-buildpack-latest
  type: pivnet
  check_every: {{poll_interval}}
  source:
    api_token: {{pcf_pivnet_token}}
    product_slug: buildpacks
    product_version: "PHP*"

- name: python-buildpack-latest
  type: pivnet
  check_every: {{poll_interval}}
  source:
    api_token: {{pcf_pivnet_token}}
    product_slug: buildpacks
    product_version: "Python*"

- name: ruby-buildpack-latest
  type: pivnet
  check_every: {{poll_interval}}
  source:
    api_token: {{pcf_pivnet_token}}
    product_slug: buildpacks
    product_version: "Ruby*"

- name: staticfile-buildpack-latest
  type: pivnet
  check_every: {{poll_interval}}
  source:
    api_token: {{pcf_pivnet_token}}
    product_slug: buildpacks
    product_version: "Staticfile*"

- name: tcserver-buildpack-latest
  type: pivnet
  check_every: {{poll_interval}} 
  source:
    api_token: {{pcf_pivnet_token}}
    product_slug: buildpacks
    product_version: "tc Server*"

jobs:
- name: download-buildbacks
  plan:
  - get: binary-buildpack-latest
  - get: dotnetcore-buildpack-latest
  - get: go-buildpack-latest
  - get: java-buildpack-latest
    params:
      globs:
      - "*offline*"
  - get: nodejs-buildpack-latest
  - get: php-buildpack-latest
  - get: python-buildpack-latest
  - get: ruby-buildpack-latest
  - get: staticfile-buildpack-latest
  - get: tcserver-buildpack-latest
