resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final
resources:
- name: task-bundle-release
  type: github-release
  source:
    user: c0-ops
    repository: concourse-tasks-bundle
    access_token: {{github_token}}
    pre_release: true
- name: tc-buildpack-latest
  type: pivnet
  check_every: {{poll_interval}}
  source:
    api_token: {{pcf_pivnet_token}}
    product_slug: buildpacks
    product_version: tc*

jobs:
- name: download-buildpacks
  plan:
  - aggregate:
    - get: task-bundle-release
      version: { tag: 'v0.0.11' }
    - get: tc-buildpack-latest
      trigger: true
  - task: unpack-tasks
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: cloudfoundry/cflinuxfs2
      inputs:
      - name: task-bundle-release
      outputs:
      - name: concourse-tasks-bundle
      run:
        path: sh
        args:
        - -exc
        - |
         tar xvzf task-bundle-release/tasks-bundle.tgz -C concourse-tasks-bundle
  - task: update-tc-buildpack
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: cloudfoundry/cflinuxfs2
      inputs:
      - name: tc-buildpack-latest
      - name: concourse-tasks-bundle
      params:
        PCF_API_URI: {{pcf_api_uri}}
        PCF_ORG: {{pcf_org}}
        PCF_USERNAME: {{pcf_username}}
        PCF_PASSWORD: {{pcf_password}}
        PCF_SPACE: {{pcf_space}}
        BUILDPACK_PREFIX: tc
      run:
        path: ./concourse-tasks-bundle/upgrade-buildpack/task.sh
