---
platform: linux

image_resource:
  type: docker-image
  source: {repository: cloudfoundry/cflinuxfs2}

inputs:
  - name: aws-cli
  - name: pcf-pipelines

run:
  path: pcf-pipelines/tasks/deploy-opsman-vm-aws/task.sh

params:
  AWS_SECRET_ACCESS_KEY:
  AWS_ACCESS_KEY_ID:  
  OPSMAN_TIMEOUT:
  OPSMAN_IP:
  NETMASK:
  GATEWAY:
  DNS:
  NTP:
  OPSMAN_ADMIN_PASSWORD:
  OPSMAN_NETWORK:
