groups: []

resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final

resources:
## Uncomment the below snippet to only let the pipeline run between midnight and 1am central time.
## If a change is detected earlier the pipeline will start but be held up waiting for the time
## resource to become available.
## Also uncomment the fetching of the resource in the plan below.
#- name: run-time-window
#  type: time
#  source:
#    start: 12:00 AM
#    stop: 1:00 AM
#    location: America/Chicago

- name: pcf-pipelines
  type: git
  source:
    uri: https://github.com/c0-ops/pcf-pipelines.git
    username: {{github_token}}
    password: x-oauth-basic
    branch: master

- name: tool-om
  type: github-release
  source:
    user: pivotal-cf
    repository: om
    username: {{github_token}}
    password: x-oauth-basic

- name: {{resource_name}}
  type: pivnet
  check_every: {{poll_interval}}
  source:
    api_token: {{pivnet_token}}
    product_slug: {{product_slug}}
    product_version: {{product_version}}
    sort_by: semver

- name: stemcell-downloader
  type: github-release
  source:
    user: c0-ops
    repository: pcf-product-stemcell-downloader
    access_token: {{github_token}}
    globs:
    - stemcell-downloader-linux

jobs:
- name: upgrade-tile
  plan:
  - aggregate:
    - get: pcf-pipelines
## Uncomment to limit when the pipeline can run
#   - get: run-time-window
    - get: pivnet-product
      resource: {{resource_name}}
      trigger: true
      params:
        globs:
        - "*pivotal"
    - get: tool-om
      params:
        globs:
        - om-linux
    - get: stemcell-downloader
      params:
        globs: [stemcell-downloader-linux]
  - task: upload-tile
    file: pcf-pipelines/tasks/upload-product/task.yml
    params:
      OPSMAN_USERNAME: {{opsman_admin_username}}
      OPSMAN_PASSWORD: {{opsman_admin_password}}
      OPSMAN_URI: {{opsman_uri}}
      PIVNET_PRODUCT_NAME: {{product_slug}}
  - task: stage-tile
    file: pcf-pipelines/tasks/stage-product/task.yml
    params:
      OPSMAN_USERNAME: {{opsman_admin_username}}
      OPSMAN_PASSWORD: {{opsman_admin_password}}
      OPSMAN_URI: {{opsman_uri}}
      PRODUCT_NAME: {{product_name}}
  - task: upload-stemcell
    file: pcf-pipelines/tasks/upload-stemcell/task.yml
    params:
      PRODUCT: {{metadata_basename}}
      IAAS_TYPE: {{iaas_type}}
      OPSMAN_USERNAME: {{opsman_admin_username}}
      OPSMAN_PASSWORD: {{opsman_admin_password}}
      OPSMAN_URI: {{opsman_uri}}
  - task: apply-changes
    file: pcf-pipelines/tasks/apply-changes/task.yml
    params:
      OPSMAN_USERNAME: {{opsman_admin_username}}
      OPSMAN_PASSWORD: {{opsman_admin_password}}
      OPSMAN_URI: {{opsman_uri}}
      OPSMAN_TIMEOUT: {{opsman_timeout_seconds}}
