---
platform: linux

image_resource:
  type: docker-image
  source: {repository: cloudfoundry/cflinuxfs2}

inputs:
  - name: pcf-pipelines
  - name: tool-om

outputs:
  - name: diagnostic-report

params:
  OPSMAN_USERNAME:
  OPSMAN_PASSWORD:
  OPSMAN_URI:

run:
  path: pcf-pipelines/tasks/export-opsmgr-diagnostic-report/task.sh
