resources:
- name: pcf-pipelines
  type: git
  source:
    uri: git@github.com:pivotal-cf/pcf-pipelines.git
    branch: master
    private_key: {{git_private_key}}

jobs:
- name: create-slot5-install-pcf-pipeline
  plan:
  - get: pcf-pipelines
  - task: create-config
    params:
      CONFIG: {{slot5_params}}
    file: pcf-pipelines/ci/tasks/create_multiline_config.yml
  - task: create-pipeline
    input_mapping: { release: pcf-pipelines }
    file: pcf-pipelines/ci/tasks/set_pipeline.yml
    params:
      PIPELINE_NAME: slot5-install-pcf
      PIPELINE_PATH: release/install-pcf/vsphere/pipeline.yml
      ATC_EXTERNAL_URL: {{atc_external_url}}
      ATC_BASIC_AUTH_USERNAME: {{fly_basic_auth_username}}
      ATC_BASIC_AUTH_PASSWORD: {{fly_basic_auth_password}}
      ATC_TEAM_NAME: {{atc_team_name}}

- name: destroy-slot5-install-pcf-pipeline
  plan:
  - get: pcf-pipelines
  - task: destroy
    file: pcf-pipelines/ci/tasks/destroy_pipeline.yml
    params:
      PIPELINE_NAME: slot5-install-pcf
      ATC_EXTERNAL_URL: {{atc_external_url}}
      ATC_BASIC_AUTH_USERNAME: {{fly_basic_auth_username}}
      ATC_BASIC_AUTH_PASSWORD: {{fly_basic_auth_password}}
      ATC_TEAM_NAME: {{atc_team_name}}
