groups:
- name: ert-upgrade
  jobs:
  - upload-{{pivnet_product_name}}
  - stage-{{pivnet_product_name}}
  - stage-stemcell-{{pivnet_product_name}}
  - apply-changes-{{pivnet_product_name}}

resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final

resources:
- name: pcf-pipelines
  type: git
  source:
    uri: https://github.com/c0-ops/pcf-pipelines
    branch: master

- name: tool-om
  type: github-release
  source:
    user: pivotal-cf
    repository: om
    access_token: {{github_token}}

- name: pivnet-product
  type: pivnet
  check_every: {{poll_interval}} 
  source:
    api_token: {{pcf_pivnet_token}}
    product_slug: {{pivnet_product_name}}
    product_version: {{ert_major_minor_version}}
    sort_by: semver

jobs:
- name: upload-{{pivnet_product_name}}
  plan:
  - aggregate:
    - get: pcf-pipelines
    - get: pivnet-product
      trigger: true
      params:
        globs:
        - "*pivotal"
    - get: tool-om
      params:
        globs:
        - om-linux

  - task: upload-product
    file: pcf-pipelines/tasks/upload-product/task.yml
    params:
      OPSMAN_USERNAME: {{opsman_admin_username}}
      OPSMAN_PASSWORD: {{opsman_admin_password}}
      OPSMAN_URI: {{opsman_uri}}
      PIVNET_PRODUCT_NAME: {{pivnet_product_name}}

- name: stage-{{pivnet_product_name}}
  plan:
  - aggregate:
    - get: pcf-pipelines
      passed: [upload-{{pivnet_product_name}}]
    - get: pivnet-product
      trigger: true
      passed: [upload-{{pivnet_product_name}}]
      params:
        globs:
        - "*pivotal"
    - get: tool-om
      params:
        globs:
        - om-linux

  - task: stage-product
    file: pcf-pipelines/tasks/stage-product/task.yml
    params:
      OPSMAN_USERNAME: {{opsman_admin_username}}
      OPSMAN_PASSWORD: {{opsman_admin_password}}
      OPSMAN_URI: {{opsman_uri}}
      PRODUCT_NAME: {{opsman_product_name}}

- name: stage-stemcell-{{pivnet_product_name}}
  plan:
  - aggregate:
    - get: pcf-pipelines
      passed: [stage-{{pivnet_product_name}}]
    - get: pivnet-product
      trigger: true
      passed: [stage-{{pivnet_product_name}}]
      params:
        globs:
        - "*pivotal"
      passed: [stage-{{pivnet_product_name}}]
    - get: tool-om
      params:
        globs:
        - om-linux

  - task: download-stemcell
    file: pcf-pipelines/tasks/download-bosh-io-stemcell/task.yml
    params:
      PRODUCT: {{opsman_product_name}}
      IAAS_TYPE: {{iaas_type}}

  - task: upload-stemcell
    file: pcf-pipelines/tasks/upload-stemcell/task.yml
    params:
      OPSMAN_USERNAME: {{opsman_admin_username}}
      OPSMAN_PASSWORD: {{opsman_admin_password}}
      OPSMAN_URI: {{opsman_uri}}

- name: apply-changes-{{pivnet_product_name}}
  plan:
  - aggregate:
    - get: pcf-pipelines
      passed: [stage-stemcell-{{pivnet_product_name}}]
    - get: tool-om
      params:
        globs:
        - om-linux

  - task: apply-changes
    file: pcf-pipelines/tasks/apply-changes/task.yml
    params:
      OPSMAN_USERNAME: {{opsman_admin_username}}
      OPSMAN_PASSWORD: {{opsman_admin_password}}
      OPSMAN_URI: {{opsman_uri}}
