---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: czero/cflinuxfs2
inputs:
  - name: pcf-pipelines 

params:
  pcf_ert_domain:
  pcf_opsman_admin:
  pcf_opsman_admin_passwd:
  OPSMAN_CLIENT_ID:
  OPSMAN_CLIENT_SECRET:

run:
  path: pcf-pipelines/install-pcf/aws/tasks/deploy-director/task.sh
