resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final

resources:
- name: tool-om
  type: github-release
  source:
    user: c0-ops
    repository: om
    access_token: {{github_token}}

- name: pcf-pipelines
  type: git
  source:
    uri: git@github.com:c0-ops/pcf-pipelines
    branch: master

- name: pivnet-opsmgr
  type: pivnet
  source:
    api_token: {{pcf_pivnet_token}}
    product_slug: ops-manager
    sort_by: semver

jobs:
- name: upgrade-opsmgr
  plan:
  - aggregate:
    - get: pcf-pipelines
    - get: tool-om
      globs: om-linux
    - get: pivnet-opsmgr
      params:
        globs:
        - "*.ova"

  - task: export-opsmgr
    file: pcf-pipelines/tasks/export-opsmgr-settings/task.yml
    params:
      OPSMAN_USERNAME: {{opsman_admin_username}}
      OPSMAN_PASSWORD: {{opsman_admin_password}}
      OPSMAN_URI: {{opsman_uri}}
      OPSMAN_SETTINGS_FILENAME: installation.zip

  - task: deploy-opsman-vm
    file: pcf-pipelines/tasks/deploy-opsman-vm/task.yml
    params:
      GOVC_USERNAME: {{vcenter_username}}
      GOVC_PASSWORD: {{vcenter_password}}
      GOVC_DATACENTER: {{vcenter_datacenter}}
      GOVC_CLUSTER: {{vcenter_cluster}}
      GOVC_DATASTORE: {{vcenter_datastore}}
      GOVC_RESOURCE_POOL: {{vcenter_resource_pool}}
      GOVC_URL: {{vcenter_url}}
      OPSMAN_IP: {{opsman_ip}}
      NETMASK: {{netmask}}
      GATEWAY: {{gateway}}
      DNS: {{dns}}
      NTP: {{ntp}}
      OPSMAN_NETWORK: {{opsman_network}}
      OPSMAN_VM_FOLDER: {{opsman_vm_folder}}
      OPSMAN_ADMIN_PASSWORD: {{opsman_admin_password}}

  - task: import-opsmgr
    file: pcf-pipelines/tasks/import-opsmgr-settings/task.yml
    params:
      OPSMAN_USERNAME: {{opsman_admin_username}}
      OPSMAN_PASSWORD: {{opsman_admin_password}}
      OPSMAN_URI: {{opsman_uri}}
      OPSMAN_SETTINGS_FILENAME: installation.zip
      OPSMAN_PASSPHRASE: {{opsman_passphrase}}

      # todo discuss the order for calling this task
  # - task: apply-changes
  #   file: pcf-pipelines/tasks/apply-changes/task.yml
  #   params:
  #     OPSMAN_USERNAME: {{opsman_admin_username}}
  #     OPSMAN_PASSWORD: {{opsman_admin_password}}
  #     OPSMAN_URI: {{opsman_uri}}
