resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final

resources:
- name: task-bundle-release
  type: github-release
  source:
    user: c0-ops
    repository: concourse-tasks-bundle
    access_token: {{github_token}}
    drafts: true
- name: pivnet-opsmgr
  type: pivnet
  source:
    api_token: {{pcf_pivnet_token}}
    product_slug: ops-manager
    sort_by: semver

jobs:
- name: upgrade-opsmgr
  plan:
  - aggregate:
    - get: task-bundle-release
    - get: pivnet-opsmgr
      params:
        globs:
        - "*.ova"

  - task: unpack-tasks
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: cloudfoundry/cflinuxfs2
      inputs:
      - name: task-bundle-release
      outputs:
      - name: concourse-tasks-bundle
      run:
        path: tar
        args:
        - -C
        - concourse-tasks-bundle
        - -xvzf
        - task-bundle-release/tasks-bundle.tgz

  - task: export-opsmgr
    file: concourse-tasks-bundle/export-opsmgr-settings/task.yml
    params:
      OPSMAN_USERNAME: {{opsman_admin_username}}
      OPSMAN_PASSWORD: {{opsman_admin_password}}
      OPSMAN_URI: {{opsman_uri}}
      OPSMAN_SETTINGS_FILENAME: installation.zip

  - task: deploy-opsman-vm
    file: concourse-tasks-bundle/deploy-opsman-vm/task.yml
    params:
      GOVC_USERNAME: {{vcenter_username}}
      GOVC_PASSWORD: {{vcenter_password}}
      GOVC_DATACENTER: {{vcenter_datacenter}}
      GOVC_CLUSTER: {{vcenter_cluster}}
      GOVC_DATASTORE: {{vcenter_datacenter}}
      GOVC_RESOURCE_POOL: {{vcenter_resource_pool}}
      OPSMAN_IP: {{opsman_ip}}
      NETMASK: {{netmask}}
      GATEWAY: {{gateway}}
      DNS: {{dns}}
      NTP: {{ntp}}
      OPSMAN_NETWORK: {{opsman_network}}
      OPSMAN_VM_FOLDER: {{opsman_vm_folder}}
      OPSMAN_ADMIN_PASSWORD: {{opsman_admin_password}}

  - task: import-opsmgr
    file: concourse-tasks-bundle/import-opsmgr-settings/task.yml
    params:
      OPSMAN_USERNAME: {{opsman_admin_username}}
      OPSMAN_PASSWORD: {{opsman_admin_password}}
      OPSMAN_URI: {{opsman_uri}}
      OPSMAN_SETTINGS_FILENAME: installation.zip
      OPSMAN_PASSPHRASE: {{opsman_passphrase}}

      # todo discuss the order for calling this task
  # - task: apply-changes
  #   file: concourse-tasks-bundle/apply-changes/task.yml
  #   params:
  #     OPSMAN_USERNAME: {{opsman_admin_username}}
  #     OPSMAN_PASSWORD: {{opsman_admin_password}}
  #     OPSMAN_URI: {{opsman_uri}}
