resources:
- name: pcf-pipelines
  type: git
  source:
    uri: git@github.com:pivotal-cf/pcf-pipelines.git
    branch: master
    private_key: {{git_private_key}}
    paths: [ci/Dockerfile]

- name: pcf-pipelines-image
  type: docker-image
  source:
    repository: czero/cflinuxfs2
    tag: latest
    username: czero
    password: {{czero_dockerhub_password}}

- name: cflinuxfs2
  type: docker-image
  source:
    repository: cloudfoundry/cflinuxfs2
    tag: latest

- name: om
  type: github-release
  source:
    user: pivotal-cf
    repository: om
    access_token: {{github_token}}

- name: cf-cli-tarball
  type: s3
  source:
    bucket: cf-cli-releases
    regexp: releases/v([\d\.]+)/cf-cli_.*_linux_x86-64.tgz
    region_name: us-west-1

jobs:
- name: build-pcf-pipelines-image
  serial: true
  plan:
  - aggregate:
    - get: pcf-pipelines
      trigger: true
    - get: om
      params: {globs: ["*linux*"]}
    - get: cflinuxfs2
      trigger: true
      params: {save: true}
    - get: cf-cli-tarball

  - task: prepare-workspace
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: busybox}
      inputs:
      - name: om
      - name: cf-cli-tarball
      - name: pcf-pipelines
      outputs:
      - name: workspace
      run:
        path: sh
        args:
        - -c
        - |
          cp pcf-pipelines/ci/Dockerfile workspace

          cp om/om-linux workspace
          chmod +x workspace/om-linux

          tar -C workspace -xf cf-cli-tarball/*.tgz cf
          chmod +x workspace/cf

  - put: pcf-pipelines-image
    params:
      load_base: cflinuxfs2
      build: workspace
