---
platform: linux

image_resource:
  type: docker-image
  source: {repository: cloudfoundry/cflinuxfs2}

inputs:
  - name: pcf-pipelines
  - name: tool-om

params:
  OPSMAN_USERNAME:
  OPSMAN_PASSWORD:
  OPSMAN_URI:

run:
  path: pcf-pipelines/tasks/wait-opsman-clear/task.sh
